project:
  type: website

website:
  title: "High Power Rocketry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro/
        text: Intro  
      - href: safety/
        text: Safety
      - href: const/
        text: Construction
      - href: model/
        text: Modeling
      - href: instr/
        text: "Data Analysis"
      - href: fltdata/
        text: "Flight Data"
      - href: archive/
        text: Archive

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

execute:
  freeze: auto



